#################
### AUTOSTART ###
#################
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = systemctl --user start hyprpolkitagent
exec-once = waypaper --restore
exec-once = waybar
exec-once = vicinae server 
exec-once = swaync -c ~/.config/swaync/config.json
exec-once = systemctl --user enable --now veilad.service
exec-once = discover-overlay
exec-once = export QT_STYLE_OVERRIDE=Orchis-Dark
exec-once = gpu-screen-recorder
# exec-once = wal -R
# exec-once = quickshell
# exec-once = awww-daemon
# exec-once = matugen image ~/path/to/default/wallpaper.jpg -m dark --source-color-index 0