general {
    lock_cmd = veila lock --wait-ready              # veila screen lock
    before_sleep_cmd = veila lock --wait-ready      # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on      # wake display after sleep
    inhibit_sleep = 3
}

# Dim the screen first (optional)
listener {
    timeout = 150                                   # 2.5 minutes
    on-timeout = brightnessctl -s set 10%           # set monitor backlight to 10%
    on-resume = brightnessctl -r                    # restore monitor backlight
}

# Lock the screen (Visible)
listener {
    timeout = 300                                   # 5 minutes
    on-timeout = veila lock --wait-ready            # lock screen (stays visible)
}

# Turn off the screen (Black out)
listener {
    timeout = 600                                   # 10 minutes (5 mins after locking)
    on-timeout = hyprctl dispatch dpms off          # turn off display
    on-resume = hyprctl dispatch dpms on            # turn on display
}