general {
    lock_cmd = pidof hyprlock || hyprlock       # command ran when locking
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on screen after suspend
}

listener {
    timeout = 300                                # 5 min
    on-timeout = loginctl lock-session          # lock screen
}

listener {
    timeout = 330                                # 5.5 min
    on-timeout = hyprctl dispatch dpms off      # screen off
    on-resume = hyprctl dispatch dpms on        # screen on
}
