#################
### AUTOSTART ###
#################
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = systemctl --user start hyprpolkitagent
exec-once = waypaper --restore
exec-once = waybar
exec-once = vicinae server 
# exec-once = quickshell
exec-once = swaync -c ~/.config/swaync/config.json
exec-once = wal -R
exec-once = systemctl --user enable --now veilad.service
exec-once = discover-overlay
exec-once = export QT_STYLE_OVERRIDE=Orchis-Dark
