bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 10%+
bindel = ,XF86MonBrightnessUp SHIFT, exec, brightnessctl -e4 -n2 set 1%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 10%-
bindel = ,XF86MonBrightnessDown SHIFT, exec, brightnessctl -e4 -n2 set 1%-