$menu = wofi     
$mainMod = SUPER
$terminal = kitty                 
$browser = zen-browser
$fileManager = thunar           
$musicPlayer = com.spotify.Client # flatpak version - iirc, aur version is "spotify"
###################################

######################################
## Binds with $mainMod + single key ##
######################################

bind = $mainMod alt, escape, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit # Logout to SDDM
bind = $mainMod, C, killactive, # Kills focused tab
bind = $mainMod, code:61, exec, [focus; float; 350 350] hyprkcs # Opens Bind Manager #Forward Slash 
bind = $mainMod, E, exec, $fileManager # Opens File Manager
bind = $mainMod, F, fullscreen # Fullscreen
bind = $mainMod, L, exec, veila lock # Locks Scren
bind = $mainMod, N, exec, swaync-client -t -sw # Notification Manager
bind = $mainMod, R, exec, [focus; float; 100 100] $terminal # terminal
bind = $mainMod, S, layoutmsg, togglesplit dwindle # Switches split type
bind = $mainMod, Space, exec, vicinae toggle # Opens Search bar (vicinae)
bind = $mainMod, T, exec, $terminal # Opens terminal (group)
bind = $mainMod, V, togglefloating, # toggle floating
bind = $mainMod, W, exec, killall -SIGUSR1 waybar # hide waybar
bind = $mainMod, Z, exec, $browser # zen browser

############################################
## unused binds for $mainmod + single key ##
############################################
 bind = $mainMod, A, exec, /home/komari/.config/matugen/spice.sh
 bind = $mainMod, B, exec, /home/komari/.config/wofi/scripts/changeWallpaper2
 bind = $mainMod, D, exec, /home/komari/.config/wofi/scripts/wallpaper-switcher2
# bind = $mainMod, G,
# bind = $mainMod, H,
# bind = $mainMod, I,
# bind = $mainMod, J,
# bind = $mainMod, K,
# bind = $mainMod, M,
# bind = $mainMod, O,
# bind = $mainMod, P,
# bind = $mainMod, Q,
# bind = $mainMod, S,
# bind = $mainMod, U,
# bind = $mainMod, X,
# bind = $mainMod, Y,



##########################################
## Binds with $mainMod + modifier + key ##
##########################################

bind = SUPER Alt, C, exec, vicinae vicinae://launch/clipboard/history # Opens Clipboard via Vicinae
bind = $mainMod Alt, S, exec, $musicPlayer # Opens the music player (spotfy)

bind = $mainMod shift, W, exec, killall -SIGUSR2 waybar # Reloads Waybar
bind = $mainMod,Print, exec, hyprshot -m region # Screenshots a selected region
bind = $mainMod SHIFT, D, exec,[focus; float; 100 100] waypaper # Opens Wallpaper Switcher

################################################
## unused binds for $mainMod + modifier + key ##
################################################

# bind = $mainMod Alt, B,
# bind = $mainMod Shift, B,
# bind = $mainMod Alt, G,
# bind = $mainMod Shift, G,
# bind = $mainMod Alt, H,
# bind = $mainMod Shift, H,
# bind = $mainMod Alt, I,
# bind = $mainMod Shift, I,
# bind = $mainMod Alt, J,
# bind = $mainMod Shift, J,
# bind = $mainMod Alt, K,
# bind = $mainMod Shift, K,
# bind = $mainMod Alt, M,
# bind = $mainMod Shift, M,
# bind = $mainMod Alt, O,
# bind = $mainMod Shift, O,
# bind = $mainMod Alt, P,
# bind = $mainMod Shift, P,
# bind = $mainMod Alt, Q,
# bind = $mainMod Shift, Q,
# bind = $mainMod Alt, U,
# bind = $mainMod Shift, U,
# bind = $mainMod Alt, X,
# bind = $mainMod Shift, X,
# bind = $mainMod Alt, Y,
# bind = $mainMod Shift, Y,
# bind = $mainMod Alt, Z,
# bind = $mainMod Shift, Z,



# bind = ,Print, exec, hyprshot -m window # commented out because of gpu-screenrecorders built in screenshot functions
# bind = $mainMod SHIFT, Print, exec, 


