[background]
mode = "file"
path = "/home/komari/Pictures/Wallpapers/clay-banks-u27Rrbs9Dwc-unsplash.png"
color = "#000000"
dim_strength = 64

[battery]
enabled = false

[weather]
enabled = false

[visuals.clock]
format = "12h"
style = "standard"
meridiem_font_size = 22
meridiem_x = 6
meridiem_y = 7
font_family = "Geom"
font_weight = 600
color = "#ffffff"
font_size = 88
halign = "center"
valign = "top"
x = 0
y = 40

[visuals.date]
format = "long"
font_family = "Google Sans Flex"
font_weight = 400
font_size = 18
color = "#ffffff"
halign = "center"
valign = "top"
x = 0
y = 140

[visuals.input]
placeholder = "Password"
background_color = "rgba(0, 0, 0, 0.08)"
width = 310
height = 54
radius = 50
mask_color = "#ffffff"
font_family = "Google Sans Flex"
font_weight = 400
font_size = 16
border_color = "rgb(255, 255, 255)"
border_width = 3
halign = "center"
valign = "bottom"
x = 0
y = -30

[visuals.status]
mode = "inline"
rejected_color = "#FFD5D5"
pending_color = "#ECECEC"

[visuals.eye]
color = "rgba(255, 255, 255, 0.72)"

[visuals.caps_lock]
color = "rgba(255, 255, 255, 0.52)"

[visuals.placeholder]
color = "rgba(255, 255, 255, 0.6)"

[visuals.avatar]
enabled = false
image_path = "/home/komari/Pictures/pfps/full layoura/badGuy Soueater/d27671faf02e1f0cad113fc58e70537a.jpg"
size = 150
background_color = "rgba(255, 255, 255, 0.04)"
placeholder_padding = 28
ring_color = "rgba(255, 255, 255, 0.15)"
ring_width = 3
icon_color = "#ffffff"
halign = "center"
valign = "bottom"
x = 0
y = -350

[visuals.username]
enabled = false
font_family = "Google Sans Flex"
font_weight = 400
color = "rgba(255, 255, 255, 0.84)"
font_size = 28
halign = "center"
valign = "center"
x = 0
y = -135

[visuals.keyboard]
enabled = false
background_size = 46
radius = 23
background_color = "rgba(255, 255, 255, 0.05)"
color = "rgba(255, 255, 255, 0.68)"
size = 16
halign = "right"
valign = "top"
x = -24
y = 21

[visuals.battery]
background_color = "rgba(255, 255, 255, 0.05)"
background_size = 46
radius = 23
color = "rgb(255, 255, 255)"
size = 20
halign = "right"
valign = "top"
x = -78
y = 21

[visuals.weather.icon]
size = 40
opacity = 80
halign = "left"
valign = "bottom"
x = 40
y = -112

[visuals.weather.temperature]
font_size = 40
font_family = "Google Sans Flex"
font_weight = 400
letter_spacing = 0
color = "rgb(255, 255, 255)"
halign = "left"
valign = "bottom"
x = 40
y = -70

[visuals.weather.location]
font_size = 22
font_family = "Google Sans Flex"
font_weight = 400
color = "rgb(255, 255, 255)"
halign = "left"
valign = "bottom"
x = 40
y = -44

[visuals.now_playing]
enabled = false
fade_duration_ms = 320
halign = "center"
valign = "bottom"

[visuals.now_playing.artwork]
enabled = true
size = 44
radius = 8
opacity = 90
halign = "center"
valign = "bottom"
x = 10
y = 0
relative_to = "now_playing"

[visuals.now_playing.artist]
width = 318
color = "rgb(255, 255, 255)"
font_family = "Google Sans Flex"
font_size = 16
font_weight = 400
halign = "center"
valign = "bottom"
x = 65
y = 10
relative_to = "now_playing"

[visuals.now_playing.title]
width = 318
color = "rgb(255, 255, 255)"
font_family = "Google Sans Flex"
font_size = 16
font_weight = 400
halign = "center"
valign = "bottom"
x = 65
y = -10
relative_to = "now_playing"

# Now playing backdrop
[[visuals.backdrop]]
enabled = true
name = "now_playing"
show_when = "now_playing"
mode = "blur"
color = "rgba(18, 18, 18, 0.02)"
blur_strength = 12
radius = 10
border_color = "#ffffff"
width = 400
height = 60
halign = "center"
valign = "bottom"
x = -40
y = -40
z = 1